/* eslint-disable no-undef */
import React from 'react';
import {View, SafeAreaView, StatusBar, Dimensions, StyleSheet, ScrollView} from 'react-native';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import SelectDropdown from 'react-native-select-dropdown';


export default Countires = () => {
  const countires = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cote dIvoire',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia (Czech Republic)',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini (fmr. "Swaziland")',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
  const Countriesdata = [
    {title:'Afghanistan',},
    {title:'Albania',},
    {title:'Algeria',},
    {title:'Andorra',},
    {title:'Angola',},
    {title:'Antigua and Barbuda',},
    {title:'Argentina',},
    {title:'Armenia',},
    {title:'Australia',},
    {title:'Austria',},
    {title:'Azerbaijan',},
    {title:'Bahamas',},
    {title:'Bahrain',},
    {title:'Bangladesh',},
    {title:'Barbados',},
    {title:'Belarus',},
    {title:'Belgium',},
    {title:'Belize',},
    {title:'Benin',},
    {title:'Bhutan',},
    {title:'Bolivia',},
    {title:'Bosnia and Herzegovina',},
    {title:'Botswana',},
    {title:'Brazil',},
    {title:'Brunei',},
    {title:'Bulgaria',},
    {title:'Burkina Faso',},
    {title:'Burundi',},
    {title:'Cote dIvoire',},
    {title:'Cabo Verde',},
    {title:'Cambodia',},
    {title:'Cameroon',},
    {title:'Canada',},
    {title:'Central African Republic',},
    {title:'Chad',},
    {title:'Chile',},
    {title:'China',},
    {title:'Colombia',},
    {title:'Comoros',},
    {title:'Congo (Congo-Brazzaville)',},
    {title:'Costa Rica',},
    {title:'Croatia',},
    {title:'Cuba',},
    {title:'Cyprus',},
    {title:'Czechia (Czech Republic)',},
    {title:'Democratic Republic of the Congo',},
    {title:'Denmark',},
    {title:'Djibouti',},
    {title:'Dominica',},
    {title:'Dominican Republic',},
    {title:'Ecuador',},
    {title:'Egypt',},
    {title:'El Salvador',},
    {title:'Equatorial Guinea',},
    {title:'Eritrea',},
    {title:'Estonia',},
    {title:'Eswatini (fmr. "Swaziland")',},
    {title:'Ethiopia',},
    {title:'Fiji',},
    {title:'Finland',},
    {title:'France',},
    {title:'Gabon',},
    {title:'Gambia',},
    {title:'Georgia',},
    {title:'Germany',},
    {title:'Ghana',},
    {title:'Greece',},
    {title:'Grenada',},
    {title:'Guatemala',},
    {title:'Guinea',},
    {title:'Guinea-Bissau',},
    {title:'Guyana',},
    {title:'Haiti',},
    {title:'Holy See',},
    {title:'Honduras',},
    {title:'Hungary',},
    {title:'Iceland',},
    {title:'India',},
    {title:'Indonesia',},
    {title:'Iran',},
    {title:'Iraq',},
    {title:'Ireland',},
    {title:'Israel',},
    {title:'Italy',},
    {title:'Jamaica',},
    {title:'Japan',},
    {title:'Jordan',},
    {title:'Kazakhstan',},
    {title:'Kenya',},
    {title:'Kiribati',},
    {title:'Kuwait',},
    {title:'Kyrgyzstan',},
    {title:'Laos',},
    {title:'Latvia',},
    {title:'Lebanon',},
    {title:'Lesotho',},
    {title:'Liberia',},
    {title:'Libya',},
    {title:'Liechtenstein',},
    {title:'Lithuania',},
    {title:'Luxembourg',},
    {title:'Madagascar',},
    {title:'Malawi',},
    {title:'Malaysia',},
    {title:'Maldives',},
    {title:'Mali',},
    {title:'Malta',},
    {title:'Marshall Islands',},
    {title:'Mauritania',},
    {title:'Mauritius',},
    {title:'Mexico',},
    {title:'Micronesia',},
    {title:'Moldova',},
    {title:'Monaco',},
    {title:'Mongolia',},
    {title:'Montenegro',},
    {title:'Morocco',},
    {title:'Mozambique',},
    {title:'Myanmar (formerly Burma)',},
    {title:'Namibia',},
    {title:'Nauru',},
    {title:'Nepal',},
    {title:'Netherlands',},
    {title:'New Zealand',},
    {title:'Nicaragua',},
    {title:'Niger',},
    {title:'Nigeria',},
    {title:'North Korea',},
    {title:'North Macedonia',},
    {title:'Norway',},
    {title:'Oman',},
    {title:'Pakistan',},
    {title:'Palau',},
    {title:'Palestine State',},
    {title:'Panama',},
    {title:'Papua New Guinea',},
    {title:'Paraguay',},
    {title:'Peru',},
    {title:'Philippines',},
    {title:'Poland',},
    {title:'Portugal',},
    {title:'Qatar',},
    {title:'Romania',},
    {title:'Russia',},
    {title:'Rwanda',},
    {title:'Saint Kitts and Nevis',},
    {title:'Saint Lucia',},
    {title:'Saint Vincent and the Grenadines',},
    {title:'Samoa',},
    {title:'San Marino',},
    {title:'Sao Tome and Principe',},
    {title:'Saudi Arabia',},
    {title:'Senegal',},
    {title:'Serbia',},
    {title:'Seychelles',},
    {title:'Sierra Leone',},
    {title:'Singapore',},
    {title:'Slovakia',},
    {title:'Slovenia',},
    {title:'Solomon Islands',},
    {title:'Somalia',},
    {title:'South Africa',},
    {title:'South Korea',},
    {title:'South Sudan',},
    {title:'Spain',},
    {title:'Sri Lanka',},
    {title:'Sudan',},
    {title:'Suriname',},
    {title:'Sweden',},
    {title:'Switzerland',},
    {title:'Syria',},
    {title:'Tajikistan',},
    {title:'Tanzania',},
    {title:'Thailand',},
    {title:'Timor-Leste',},
    {title:'Togo',},
    {title:'Tonga',},
    {title:'Trinidad and Tobago',},
    {title:'Tunisia',},
    {title:'Turkey',},
    {title:'Turkmenistan',},
    {title:'Tuvalu',},
    {title:'Uganda',},
    {title:'Ukraine',},
    {title:'United Arab Emirates',},
    {title:'United Kingdom',},
    {title:'United States of America',},
    {title:'Uruguay',},
    {title:'Uzbekistan',},
    {title:'Vanuatu',},
    {title:'Venezuela',},
    {title:'Vietnam',},
    {title:'Yemen',},
    {title:'Zambia',},
    {title:'Zimbabwe',},
  ];

  return (
    <SafeAreaView style={styles.saveAreaViewContainer}>
      <StatusBar backgroundColor="#FFF" barStyle="dark-content" />
      <View style={styles.viewContainer}>
        <ScrollView
          showsVerticalScrollIndicator={false}
          alwaysBounceVertical={false}
          contentContainerStyle={styles.scrollViewContainer}>
          <SelectDropdown
            data={countires}
            onSelect={(selectedItem, index) => {
              console.log(selectedItem, index);
            }}
            defaultButtonText={'Select Countries'}
            buttonTextAfterSelection={(selectedItem, index) => {
              return selectedItem;
            }}
            rowTextForSelection={(item, index) => {
              return item;
            }}
            buttonStyle={styles.dropdown1BtnStyle}
            buttonTextStyle={styles.dropdown1BtnTxtStyle}
            renderDropdownIcon={isOpened => {
              return <FontAwesome name={isOpened ? 'chevron-up' : 'chevron-down'} color={'#444'} size={18} />;
            }}
            dropdownIconPosition={'right'}
            dropdownStyle={styles.dropdown1DropdownStyle}
            rowStyle={styles.dropdown1RowStyle}
            rowTextStyle={styles.dropdown1RowTxtStyle}
          />
        </ScrollView>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
 saveAreaViewContainer: {flex: 1, backgroundColor: '#FFF'},
  viewContainer: {flex: 1,backgroundColor: '#FFF'},
  scrollViewContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingVertical: '1%',
  },

  dropdown1BtnStyle: {
    width: Dimensions.get('window').width / 2,
    height: Dimensions.get('window').height / 25,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 5,
    borderColor: '#444',
  },
  dropdown1BtnTxtStyle: {color: '#444', textAlign: 'left', fontSize:20,fontWeight:'600',},
  dropdown1DropdownStyle: {backgroundColor: '#EFEFEF', fontSize:20,fontWeight:'600',},
  dropdown1RowStyle: {backgroundColor: '#EFEFEF', borderBottomColor: '#C5C5C5', fontSize:20,fontWeight:'600',},
  dropdown1RowTxtStyle: {color: '#444', textAlign: 'left', fontSize:20,fontWeight:'600',},
});